from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
from urllib.parse import urlparse, parse_qs

from .agent import Agent
from .simulation import SCENARIOS, make_world
from .telemetry import Recorder

PAGE = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>GPO AI Simulation</title>
<style>body{margin:0;background:#0b1020;color:#e6edf8;font:15px system-ui}header{padding:18px 24px;background:#121a2d;border-bottom:1px solid #27334d;display:flex;justify-content:space-between}main{max-width:1100px;margin:22px auto;padding:0 16px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{background:#121a2d;border:1px solid #27334d;border-radius:12px;padding:16px}.wide{grid-column:1/-1}.muted{color:#93a4bf}.big{font-size:26px;font-weight:700}.green{color:#64e6ad}.amber{color:#ffd166}button,select{background:#263552;color:#fff;border:1px solid #435578;border-radius:7px;padding:9px 12px}li{padding:4px 0}pre{white-space:pre-wrap;color:#b8c8e2;max-height:300px;overflow:auto}@media(max-width:700px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style></head><body>
<header><strong>GPO AI · Simulation Agent</strong><span class="green">● LOCAL SYNTHETIC WORLD</span></header><main><p class="muted">No game connection or desktop input. All state shown is generated by the local simulator.</p>
<p><select id="scenario"></select> <button onclick="start()">Start / Reset</button> <button onclick="step()">Step agent</button> <button onclick="run()">Run scenario</button></p>
<div class="grid"><section class="card"><div class="muted">PLAYER HEALTH</div><div class="big" id="hp">—</div><div id="state"></div></section><section class="card"><div class="muted">CURRENT DECISION</div><div class="big" id="decision">—</div><div id="reason"></div></section>
<section class="card"><h3>Perception</h3><div id="vision"></div></section><section class="card"><h3>World model</h3><div id="world"></div></section><section class="card wide"><h3>Behavior trace · safety</h3><div id="trace"></div><div id="safety" class="muted"></div></section><section class="card wide"><h3>Telemetry</h3><pre id="events">Waiting for local simulation…</pre></section></div></main>
<script>let timer;async function api(path,opts){let r=await fetch(path,opts);return r.json()}async function init(){let s=await api('/api/scenarios');scenario.innerHTML=s.map(x=>`<option>${x}</option>`).join('');await start()}async function start(){clearInterval(timer);await api('/api/start?scenario='+scenario.value,{method:'POST'});await refresh()}async function step(){await api('/api/step',{method:'POST'});await refresh()}async function run(){clearInterval(timer);for(let i=0;i<12;i++){let x=await api('/api/step',{method:'POST'});await refresh();if(x.terminal)break}}async function refresh(){let d=await api('/api/state');let w=d.world||{};hp.textContent=`${w.player_health??'—'} / 100`;state.textContent=`State: ${w.combat_state||'—'} · tick ${w.tick??0}`;decision.textContent=d.last?.action||'Observe';reason.textContent=d.last?.reason||'Ready';vision.textContent=`Target ${w.target_visible?'detected':'not detected'} · confidence ${Math.round((w.vision_confidence||0)*100)}% · ${w.targets||0} target(s)`;world.textContent=`Target HP: ${w.target_health??'—'} · distance: ${w.target_distance??'—'} · scenario: ${w.scenario||'—'}`;trace.innerHTML=(d.trace||[]).map(x=>`<div>${x[0]} <span class="muted">→ ${x[1]}</span></div>`).join('')||'Idle';safety.textContent=`Safety: ${d.stopped?'EMERGENCY STOP':'action allowlist active'} · ${d.last?.outcome||'READY'}`;events.textContent=(d.events||[]).slice(-24).map(e=>`${e.timestamp}  ${e.event} ${JSON.stringify(e).slice(0,180)}`).join('\n')||'No events';}init();setInterval(refresh,1500);</script></body></html>'''


class Dashboard:
    def __init__(self):
        self.reset("NORMAL_COMBAT")

    def reset(self, scenario):
        self.world = make_world(scenario)
        self.recorder = Recorder()
        self.agent = Agent(self.recorder)
        self.last = {}

    def state(self):
        return {"world": self.world.snapshot(), "last": self.last,
                "trace": self.agent.trace, "events": self.recorder.events,
                "stopped": self.agent.safety.stopped}


APP = Dashboard()


class Handler(BaseHTTPRequestHandler):
    def send_json(self, value):
        body = json.dumps(value).encode()
        self.send_response(200); self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1:8765")
        self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)

    def do_GET(self):
        route = urlparse(self.path).path
        if route == "/":
            body = PAGE.encode(); self.send_response(200); self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)
        elif route == "/api/state": self.send_json(APP.state())
        elif route == "/api/scenarios": self.send_json(SCENARIOS)
        else: self.send_error(404)

    def do_POST(self):
        route = urlparse(self.path)
        if route.path == "/api/start":
            name = parse_qs(route.query).get("scenario", ["NORMAL_COMBAT"])[0]
            if name not in SCENARIOS: return self.send_error(400)
            APP.reset(name); APP.recorder.emit("simulation_started", scenario=name)
            return self.send_json(APP.state())
        if route.path == "/api/step":
            APP.last = APP.agent.step(APP.world)
            return self.send_json({**APP.state(), "terminal": APP.last["terminal"]})
        self.send_error(404)

    def log_message(self, fmt, *args): pass


def serve(host="127.0.0.1", port=8765):
    server = ThreadingHTTPServer((host, port), Handler)
    print(f"Dashboard listening at http://{host}:{port} (local only; Ctrl+C to stop)")
    try: server.serve_forever()
    except KeyboardInterrupt: pass
    finally: server.server_close()
